version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - $HOME/data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - $HOME/data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  test_postgres:
    container_name: test_postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - $HOME/data/test_postgres:/data/postgres
    # env_file:
    #   - test.env # <-- separate environment file for test DB
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
    networks:
      - test_postgres

networks:
  postgres:
    driver: bridge
  test_postgres:
    driver: bridge
