name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: npm install
        working-directory: client
      - name: Cypress run
        uses: cypress-io/github-action@v5.1.0
        with:
          working-directory: client
          start: npm run dev
